<?php
/*********************/
/*                   */
/*  Version : 5.1.0  */
/*  Author  : RM     */
/*  Comment : 071223 */
/*                   */
/*********************/

if ( !defined( "IN_ZYADS" ) )
{
		exit( );
}
echo "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n<head>\r\n<meta http-equiv=\"Content-Language\" content=\"gb2312\" />\r\n<meta http-equiv=\"Pragma\" content=\"no-cache\" />\r\n<meta name=\"copyright\" content=\"Www.Zyiis.Com 盈众信息科技有限公司(中易广告联盟系统)\" />\r\n<link href=\"/templates/";
echo Z_TPL;
echo "/images/style.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n<script src=\"/javascript/jquery/jquery.js\" type=\"text/javascript\"></script>\r\n<script src=\"/javascript/function.js\" type=\"text/javascript\"></script>\r\n<title>联盟后台登入</title>\r\n<body class=\"login\" style=\"background-color:#f9f9f9;\">\t\t  \r\n<table width=\"550\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\">\r\n  <tr>\r\n    <td> </td>\r\n  </tr>\r\n</table>\r\n<table width=\"560\" height=\"360\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" class=\"login_tb\">\r\n  <tr >\r\n    <td valign=\"top\"> \r\n      <table width=\"80%\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\">\r\n        <tr>\r\n          <td colspan=\"2\">&nbsp;</td>\r\n        </tr>\r\n        <tr>\r\n          <td height=\"33\" colspan=\"2\"><strong>用户名: <font color=\"#FF0000\">*</font></strong></td>\r\n        </tr>\r\n        <tr>\r\n          <td colspan=\"2\"><input name=\"username\" type=\"text\" class=\"input_1\" id=\"username\" maxlength=\"50\" /></td>\r\n        </tr>\r\n        <tr>\r\n          <td height=\"22\" colspan=\"2\"><font color=\"#666666\">请输入您的用户名.</font></td>\r\n        </tr>\r\n        <tr>\r\n          <td height=\"33\" colspan=\"2\"><strong>密码: <font color=\"#FF0000\">*</font></strong></td>\r\n        </tr>\r\n        <tr>\r\n          <td colspan=\"2\"><input name=\"password\" type=\"password\" id=\"password\" maxlength=\"30\" class=\"input_1\"/></td>\r\n        </tr>\r\n        <tr>\r\n          <td height=\"22\" colspan=\"2\"><font color=\"#666666\">请输入您的用户名密码.</font></td>\r\n        </tr>\r\n        <tr>\r\n          <td height=\"33\" colspan=\"2\"><strong>验证码: <font color=\"#FF0000\">*</font></strong></td>\r\n        </tr>\r\n        <tr>\r\n          <td colspan=\"2\"><input name=\"checkcode\" type=\"text\" id=\"checkcode\" style=\"width:50%\" maxlength=\"4\" class=\"input_1\" />\r\n              <img src=\"";
echo "http://".$_SERVER['HTTP_HOST'];
echo "/index.php?action=imgcode\" align=\"absmiddle\"  onclick=\"refurbish();\" id=\"varImg\" /></td>\r\n        </tr>\r\n        <tr>\r\n          <td height=\"22\" colspan=\"2\"><font color=\"#666666\">请输入验证码.</font></td>\r\n        </tr>\r\n        <tr>\r\n          <td><div class=\"info\" style=\"display:none; \" id=\"info\">\r\n                  <div class=\"r1\"></div>\r\n                <div class=\"r2\"></div>\r\n                <div class=\"text\" id=\"text\"></div>\r\n                <div class=\"l1\"></div>\r\n                <div class=\"l2\"></div>\r\n</div> \r\n          </td>\r\n          <td width=\"60%\" height=\"40\"> &nbsp;\r\n            <input name=\"image\" type=\"image\" id='postlogin' src=\"/templates/";
echo Z_TPL;
echo "/image/login-post.jpg\" align=\"absmiddle\" border=\"0\" style=\"width:61px; height:31px\"/></td>\r\n        </tr>\r\n      </table>\r\n    </td>\r\n  </tr>\r\n</table>\r\n<table width=\"480\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\">\r\n  <tr>\r\n    <td>&nbsp;</td>\r\n  </tr>\r\n  <tr>\r\n    <td align=\"center\"><font color=\"#666666\">Powered by <a href=\"http://www.zyiis.com\" target=\"_blank\"><b><font color=\"#666666\">Zyiis.com</font></b></a> &nbsp;&copy; 2010</font></td>\r\n  </tr>\r\n</table>\r\n<script language=\"JavaScript\" type=\"text/javascript\">\r\nvar inputs = document.getElementsByTagName(\"input\"), i = inputs.length;\r\nwhile(i--){\r\ninputs[i].onfocus = function(){\r\nthis.className += \" focus\";\r\n};\r\ninputs[i].onblur = function(){\r\nthis.className = this.className.replace(\" focus\", \"\");\r\n};\r\n}; \r\n\$(document).ready(function() {\r\n\t\$(\"#postlogin\").click(function(){ \r\n\t\tvar username = \$(\"#username\").val();\r\n\t\tvar password = \$(\"#password\").val();\r\n\t\tvar checkcode = \$(\"#checkcode\").val();\r\n\t\tif(username.length=='0'){\r\n\t\t\thtml = '请输入用户名！';\r\n\t\t\t\$('#text').html(html);\r\n\t\t\t\$('#info').show();\r\n\t\t\treturn false;\r\n\t\t}\r\n\t\telse if(password.length=='0'){\r\n\t\t\thtml = '请输入密码！';\r\n\t\t\t\$('#text').html(html);\r\n\t\t\t\$('#info').show();\r\n\t\t\treturn false;\r\n\t\t}\r\n\t\telse if(checkcode ==''){\r\n\t\t\thtml = '验证码不能为空！';\r\n\t\t\t\$('#text').html(html);\r\n\t\t\t\$('#info').show();\r\n\t\t\treturn false;\r\n\t\t\t  \r\n\t\t}  \r\n\t\t\$('#text').html(\"正在登录......\");\r\n\t\t\$('#info').show();\r\n\t\t\$.post(\"do.php?action=postlogin\",{ username: username, password: password,checkcode: checkcode }, function(data){ \r\n\t\t\t\tif(data == 'ok'){\r\n\t\t\t\t\ttop.location.href='do.php';\r\n\t\t\t\t}\r\n\t\t\t\telse if(data == 'login_err'){\r\n\t\t\t\t\tvar html = \"登录用户名或密码错误，请重新输入！\";\r\n\t\t\t\t}\r\n\t\t\t\telse if(data == 'login_lock'){\r\n\t\t\t\t\tvar html = \"无法登录，用户已被锁定！\";\r\n\t\t\t\t}\r\n\t\t\t\telse if(data == 'checkcode')\r\n\t\t\t\t{\r\n\t\t\t\t\tvar html = \"您输入的验证码错误，请重新输入！\";\r\n\t\t\t\t}\r\n\t\t\t\telse {\r\n\t\t\t\t \r\n\t\t\t\t\tvar html = \"出现系统错误，无法登陆！\";\r\n\t\t\t\t}\t\t \r\n\t\t\t\t \$('#text').html(html);\r\n\t\t\t\t \$('#info').show();\r\n\t\t\t\t \r\n\t\t\t});  \r\n\t \t\r\n\t});\r\n});\r\n \r\n</script>\r\n";
?>
